'use server';

/**
 * @fileOverview This file defines a Genkit flow for learning from user edits to resume content.
 *
 * It includes:
 * - `learnFromUserEdits`: An async function that takes in the original and edited content,
 *   and updates the AI model to reflect the user's preferred style and content.
 * - `LearnFromUserEditsInput`: The input type for the `learnFromUserEdits` function.
 * - `LearnFromUserEditsOutput`: The output type for the `learnFromUserEdits` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema
const LearnFromUserEditsInputSchema = z.object({
  originalContent: z
    .string()
    .describe('The original resume content generated by the AI.'),
  editedContent: z
    .string()
    .describe('The resume content after the user has made edits.'),
});

export type LearnFromUserEditsInput = z.infer<typeof LearnFromUserEditsInputSchema>;

// Define the output schema
const LearnFromUserEditsOutputSchema = z.object({
  success: z
    .boolean()
    .describe(
      'Indicates whether the learning process was successful. Defaults to true.'
    )
    .default(true),
  message: z
    .string()
    .optional()
    .describe('An optional message providing feedback on the learning process.'),
});

export type LearnFromUserEditsOutput = z.infer<typeof LearnFromUserEditsOutputSchema>;

// Exported function to trigger the flow
export async function learnFromUserEdits(
  input: LearnFromUserEditsInput
): Promise<LearnFromUserEditsOutput> {
  return learnFromUserEditsFlow(input);
}

// Define the prompt
const learnFromUserEditsPrompt = ai.definePrompt({
  name: 'learnFromUserEditsPrompt',
  input: {schema: LearnFromUserEditsInputSchema},
  output: {schema: LearnFromUserEditsOutputSchema},
  prompt: `You are a resume writing expert, and you are continually improving your ability to write the best resumes possible.

You were previously asked to generate the following resume content:

{{originalContent}}

The user has edited your generated content, resulting in the following:

{{editedContent}}

Analyze the differences between the original and edited content. Identify the user's preferred style, tone, and any specific changes they made.

Based on this analysis, provide an internal message explaining how to improve future resume generations to better align with the user's preferences.  This message will not be shown to the user.

Return success=true to indicate that you have learned from the edits.
`,
});

// Define the flow
const learnFromUserEditsFlow = ai.defineFlow(
  {
    name: 'learnFromUserEditsFlow',
    inputSchema: LearnFromUserEditsInputSchema,
    outputSchema: LearnFromUserEditsOutputSchema,
  },
  async input => {
    const {output} = await learnFromUserEditsPrompt(input);
    return output!;
  }
);
